management:
  server:
    address: 0.0.0.0
    port: 8000
spring:
  application:
    name: kokomen-payment-internal
  profiles:
    include:
      - domain
      - common
      - external
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null
---
# local profile
spring:
  config:
    activate:
      on-profile: local
