CREATE TABLE tosspayments_payment (
    id BIGINT NOT NULL AUTO_INCREMENT,
    payment_key VARCHAR(200) NOT NULL,
    member_id BIGINT NOT NULL,
    order_id VARCHAR(100) NOT NULL,
    order_name VARCHAR(200) NOT NULL,
    total_amount BIGINT NOT NULL,
    metadata JSON NOT NULL,
    state ENUM('NEED_APPROVE', 'APPROVED', 'NOT_NEED_CANCEL', 'NEED_CANCEL', 'CONNECTION_TIMEOUT', 'CANCELED', 'CLIENT_BAD_REQUEST', 'SERVER_BAD_REQUEST', 'COMPLETED') NOT NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY idx_payment_payment_key (payment_key),
    UNIQUE KEY uk_payment_order_id (order_id),
    KEY idx_payment_member_id (member_id)
);

CREATE TABLE tosspayments_payment_result (
    id BIGINT NOT NULL AUTO_INCREMENT,
    tosspayments_payment_id BIGINT NOT NULL,
    type ENUM('NORMAL', 'BILLING', 'BRANDPAY') NOT NULL,
    m_id VARCHAR(200) NOT NULL,
    currency VARCHAR(100) NOT NULL,
    method VARCHAR(100),
    total_amount BIGINT NOT NULL,
    balance_amount BIGINT NOT NULL,
    tosspayments_status ENUM('READY', 'IN_PROGRESS', 'WAITING_FOR_DEPOSIT', 'DONE', 'CANCELED', 'PARTIAL_CANCELED', 'ABORTED', 'EXPIRED') NOT NULL,
    requested_at DATETIME(6) NOT NULL,
    approved_at DATETIME(6),
    last_transaction_key VARCHAR(200),
    supplied_amount BIGINT,
    vat BIGINT,
    tax_free_amount BIGINT,
    tax_exemption_amount BIGINT,
    is_partial_cancelable BOOLEAN NOT NULL DEFAULT FALSE,
    receipt_url VARCHAR(500),
    easy_pay_provider VARCHAR(50),
    easy_pay_amount BIGINT,
    easy_pay_discount_amount BIGINT,
    country VARCHAR(10),
    failure_code VARCHAR(100),
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_payment_result_payment FOREIGN KEY (tosspayments_payment_id) REFERENCES tosspayments_payment(id)
);
